version: '3.5'

services:
   mysql-wordpress:
     container_name : mysql-wordpress
     image: mysql:5.7
     volumes:
       - db_data:/var/lib/mysql
     restart: always
     environment:
       MYSQL_ROOT_PASSWORD: root
       MYSQL_DATABASE: wordpress
       #MYSQL_USER: root
       #MYSQL_PASSWORD: wordpress

   wordpress:
     container_name : wordpress-christmas
     depends_on:
       - mysql-wordpress
     image: wordpress:latest
     ports:
       - "8100:80"
     restart: always
     volumes:
       - .:/var/www/html
     environment:
       WORDPRESS_DB_HOST: mysql-wordpress:3306
       WORDPRESS_DB_USER: root
       WORDPRESS_DB_PASSWORD: root
volumes:
    db_data:
